layered-approach-in-terraform
atiknn/jeff pull request #13
Opened 2023-03-15 09:40 UTC by atiknn

2023-03-18 18:24 UTC, vladimirmukhin requested changes

2023-03-18 18:24 UTC, vladimirmukhin commented on level1/provider.tf
> +    dynamodb_table = "terraformstatedynamo"
Please let me know why you're changing this?

2023-03-18 18:24 UTC, vladimirmukhin commented on level2/data.tf
> +}
Newline is missing

2023-03-18 18:24 UTC, vladimirmukhin commented on level2/terraform.tfvars
> +environment_code = "dev"
Newline is missing

2023-03-19 16:38 UTC, atiknn commented on level1/provider.tf
> +    dynamodb_table = "terraformstatedynamo"
sorry i dont remember, may be because it was giving some error.

2023-03-20 17:30 UTC, vladimirmukhin approved these changes

2023-03-20 17:45 UTC, merged