Vpc
atiknn/jeff pull request #3
Opened 2023-01-11 19:49 UTC by atiknn

2023-01-11 20:19 UTC, vladimirmukhin requested changes
- Please move your files outside of the `learn-terraform-aws-instance` folder and put them into the root of the repository
- Please remove `aws_instance.app_server` we no longer need it

2023-01-12 16:45 UTC, atiknn commented
> * Please move your files outside of the `learn-terraform-aws-instance` folder and put them into the root of the repository
> * Please remove `aws_instance.app_server` we no longer need it

Resolved

2023-01-12 16:52 UTC, vladimirmukhin requested changes

2023-01-12 16:52 UTC, vladimirmukhin commented on main.tf
> +     access_key = "XXXX"
Hardcoding access keys inside code is bad practice even if you remove them when committing to git.
There is always a chance that you accidentally commit your access key and secret key or forget to delete them from code.

Pelase obtain your keys from environment variables or from a credential file instead

Any of these options will work well:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs#environment-variables
https://registry.terraform.io/providers/hashicorp/aws/latest/docs#shared-configuration-and-credentials-files
https://registry.terraform.io/providers/hashicorp/aws/latest/docs#using-an-external-credentials-process

2023-01-12 16:52 UTC, vladimirmukhin requested changes

2023-01-12 16:52 UTC, vladimirmukhin commented on main.tf
> +
Please remove these blank lines

2023-01-12 16:53 UTC, vladimirmukhin requested changes
Please remove `terraform.tfstate` and `terraform.tfstate.backup` from git

2023-01-12 16:58 UTC, atiknn commented on main.tf
> +
ok

2023-01-13 12:04 UTC, atiknn commented
> `rm.tfstate` and `terraform.tfs`

Resolved

2023-01-13 16:06 UTC, vladimirmukhin approved these changes

2023-01-13 16:07 UTC, merged